- hosts: server
  vars:
    - image: msfr21/cicd-jenkins:beta
    - python: python-docker
  tasks:
    - name: install python docker centos
      yum:
        name: "{{ python }}"
        state: present
      when:
      - ansible_distribution == "CentOS"
    - name: install python-pip
      apt:
        name: python-pip
        state: present
      when:
      - ansible_distribution == "Ubuntu"
    - name: uninstall python docker ubuntu
      apt:
        name: python-docker
        state: absent
      when:
      - ansible_distribution == "Ubuntu"
    - name: install docker-py
      pip:
        name: docker-py
        state: present
      when:
      - ansible_distribution == "Ubuntu"      
    - name: pull image dari docker hub
      docker_image:
        name: "{{ image }}"
        state: present
        force: yes
    - name: create comtainer
      docker_container:
        name: container_docker_jenkins
        image: "{{ image }}"
        state: present
        publish_ports:
        - 8090:80
        recreate: yes
